server:
  servlet:
    context-path: /
#

spring:
  datasource: 
    url: jdbc:mysql://localhost:3306/pmsystem?useTimezone=true&serverTimezone=Asia/Shanghai&characterEncoding=UTF-8
    username: root
    password: 651392qQ
    driver-class-name: com.mysql.cj.jdbc.Driver